#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Ryusei Matsuki
# SPDX-License-Identifier: BSD-3-Clause

import sys


def tonum(s):
    try:
        return float(s)
    except:
        return float(s)


ans = 0
for line in sys.stdin:
    ans += tonum(line)

print(ans)

